const schools = [
  {
    name: "Jayshree Periwal Global School, Jaipur",
    logo: "/images/clients/1.png",
    joined: "2022",
    principal: "Ms. Manju Khosla",
    website: "https://jpgschool.com/",
    testimonial: "",
    location: "Rajasthan",
    gallery: [
      "/images/gallery/jayshreeperiwalglobal1.jpg",
      "/images/gallery/jayshreeperiwalglobal2.jpg",
      "/images/gallery/jayshreeperiwalglobal3.jpg",
      "/images/gallery/jayshreeperiwalglobal4.jpg",
      "/images/gallery/jayshreeperiwalglobal5.jpg",
      "/images/gallery/jayshreeperiwalglobal6.jpg",
    ],
    about: "Aerobay started working with Jayshree Periwal Global School, Jaipur in 2022.",
    board: "CBSE + Cambridge",
  },
  {
    name: "Jayshree Periwal High School, Jaipur",
    logo: "/images/clients/2.png",
    joined: "2022",
    principal: "Ms. Madhu",
    website: "https://jphschool.com/",
    testimonial: "",
    location: "Rajasthan",
    gallery: [
      "/images/gallery/jayshreeperiwal1.jpg",
      "/images/gallery/jayshreeperiwal2.jpg",
      "/images/gallery/jayshreeperiwal3.jpg",
      "/images/gallery/jayshreeperiwal4.jpg",
      "/images/gallery/jayshreeperiwal5.jpg",
      "/images/gallery/jayshreeperiwal6.jpg",
    ],
    about: "Aerobay started working with Jayshree Periwal High School, Jaipur in 2022.",
    board: "CBSE",
  },
  {
    name: "Aurobindo School, Jaipur",
    logo: "/images/clients/3.png",
    joined: "2022",
    principal: "Ms. Karuna Nagpal",
    website: "https://aisraj.org/",
    testimonial: "",
    location: "Rajasthan",
    gallery: [
      "/images/gallery/aurobindo1.jpg",
      "/images/gallery/aurobindo2.jpg",
      "/images/gallery/aurobindo3.jpg",
      "/images/gallery/aurobindo4.jpg",
      "/images/gallery/aurobindo5.jpg",
      "/images/gallery/aurobindo6.jpg",
    ],
    about: "Aerobay started working with Aurobindo School, Jaipur in 2022.",
    board: "CBSE",
  },
  {
    name: "RN Saha International School, Mumbai",
    logo: "/images/clients/4.png",
    joined: "2022",
    principal: "Ms. Payal Gupta",
    website: "https://rnsis.edu.in/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/rnshah1.jpg",
      "/images/gallery/rnshah2.jpg",
      "/images/gallery/rnshah3.jpg",
      "/images/gallery/rnshah4.jpg",
      "/images/gallery/rnshah5.jpg",
      "/images/gallery/rnshah6.jpg",
    ],
    about: "Aerobay started working with RN Saha International School, Mumbai in 2022.",
    board: "Cambridge",
  },
  {
    name: "SVIS, Mumbai",
    logo: "/images/clients/5.png",
    joined: "2022",
    principal: "Ms. Saibala Shetty",
    website: "https://svischool.com/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/svims1.jpg",
      "/images/gallery/svims2.jpg",
      "/images/gallery/svims3.jpg",
      "/images/gallery/svims4.jpg",
      "/images/gallery/svims5.jpg",
      "/images/gallery/svims6.jpg",
    ],
    about: "Aerobay started working with SVIS, Mumbai in 2022.",
    board: "Cambridge",
  },
  {
    name: "AM NAIK School, Mumbai",
    logo: "/images/clients/6.png",
    joined: "2022",
    principal: "Dr. Madhura Phadke",
    website: "https://amnaikschool.in/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/amnaikschool1.jpg",
      "/images/gallery/amnaikschool2.jpg",
      "/images/gallery/amnaikschool3.jpg",
      "/images/gallery/amnaikschool4.jpg",
      "/images/gallery/amnaikschool5.jpg",
      "/images/gallery/amnaikschool6.jpg",
    ],
    about: "Aerobay started working with AM NAIK School, Mumbai in 2022.",
    board: "CBSE + Cambridge",
  },
  {
    name: "DLF World School, Gr. Noida",
    logo: "/images/clients/7.png",
    joined: "2022",
    principal: "Ms. Ruchi Jain",
    website: "https://www.dlws.edu.in/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/dlfpublicschool1.jpg",
      "/images/gallery/dlfpublicschool2.jpg",
      "/images/gallery/dlfpublicschool3.jpg",
      "/images/gallery/dlfpublicschool4.jpg",
      "/images/gallery/dlfpublicschool5.jpg",
      "/images/gallery/dlfpublicschool6.jpg",
    ],
    about: "Aerobay started working with DLF World School, Gr. Noida in 2022.",
    board: "CBSE",
  },
  {
    name: "Sambhu Dayal, Ghaziabad",
    logo: "/images/clients/8.png",
    joined: "2022",
    principal: "Ms. Dr. Jyotsna Sharma",
    website: "https://sdglobalschool.com/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/shambhudayal1.jpg",
      "/images/gallery/shambhudayal2.jpg",
      "/images/gallery/shambhudayal3.jpg",
      "/images/gallery/shambhudayal4.jpg",
      "/images/gallery/shambhudayal5.jpg",
      "/images/gallery/shambhudayal6.jpg",
    ],
    about: "Aerobay started working with Sambhu Dayal, Ghaziabad in 2022.",
    board: "CBSE",
  },
  {
    name: "DLF, Ghaziabad",
    logo: "/images/clients/9.png",
    joined: "2022",
    principal: "Ms. Seema Jerath",
    website: "https://www.dlps.co.in/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/dlfpublicschool1.jpg",
      "/images/gallery/dlfpublicschool2.jpg",
      "/images/gallery/dlfpublicschool3.jpg",
      "/images/gallery/dlfpublicschool4.jpg",
      "/images/gallery/dlfpublicschool5.jpg",
      "/images/gallery/dlfpublicschool6.jpg",
    ],
    about: "Aerobay started working with DLF, Ghaziabad in 2022.",
    board: "CBSE + Cambridge",
  },
  {
    name: "Ganga International School, Delhi",
    logo: "/images/clients/10.png",
    joined: "2022",
    principal: "Ms. Swati Joshi",
    website: "https://www.gangainternationalschool.com/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/gangainternationalschool1.jpg",
      "/images/gallery/gangainternationalschool2.jpg",
      "/images/gallery/gangainternationalschool3.jpg",
      "/images/gallery/gangainternationalschool4.jpg",
      "/images/gallery/gangainternationalschool5.jpg",
      "/images/gallery/gangainternationalschool6.jpg",
    ],
    about: "Aerobay started working with Ganga International School, Delhi in 2022.",
    board: "CBSE",
  },
  {
    name: "Taurian International School, Ranchi",
    logo: "/images/clients/11.png",
    joined: "2022",
    principal: "Mr. Dr. Subhash Kumar",
    website: "https://tws.edu.in/",
    testimonial: "",
    location: "Jharkhand",
    gallery: [
      "/images/gallery/taurian1.jpg",
      "/images/gallery/taurian2.jpg",
      "/images/gallery/taurian3.jpg",
      "/images/gallery/taurian4.jpg",
      "/images/gallery/taurian5.jpg",
      "/images/gallery/taurian6.jpg",
    ],
    about: "Aerobay started working with Taurian International School, Ranchi in 2022.",
    board: "CBSE",
  },
  {
    name: "DPS School, Bokaro",
    logo: "/images/clients/12.png",
    joined: "2022",
    principal: "Dr. Awanindra singh gangwar",
    website: "https://dpsbokaro.com/dpsn/",
    testimonial: "",
    location: "Jharkhand",
    gallery: [
      "/images/gallery/dpsbokaro1.jpg",
      "/images/gallery/dpsbokaro2.jpg",
      "/images/gallery/dpsbokaro3.jpg",
      "/images/gallery/dpsbokaro4.jpg",
      "/images/gallery/dpsbokaro5.jpg",
      "/images/gallery/dpsbokaro6.jpg",
    ],
    about: "Aerobay started working with DPS School, Bokaro in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka, Bhiwani",
    logo: "/images/clients/13.png",
    joined: "2022",
    principal: "Ms. Garima Salwani",
    website: "https://gdgoenkabhiwani.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/GD1.jpg",
      "/images/gallery/GD1.jpg",
      "/images/gallery/GD1.jpg",
      "/images/gallery/GD1.jpg",
      "/images/gallery/GD1.jpg",
      "/images/gallery/GD1.jpg",
    ],
    about: "Aerobay started working with GD Goenka, Bhiwani in 2022.",
    board: "CBSE",
  },
  {
    name: "Seth MR Jaipuriya, Lucknow",
    logo: "/images/clients/14.png",
    joined: "2022",
    principal: "Ms. Dr. Reena Pathak",
    website: "https://www.jaipuriaschoolgoelcampus.in/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/sethmrjaipuriya1.jpg",
      "/images/gallery/sethmrjaipuriya2.jpg",
      "/images/gallery/sethmrjaipuriya3.jpg",
      "/images/gallery/sethmrjaipuriya4.jpg",
      "/images/gallery/sethmrjaipuriya5.jpg",
      "/images/gallery/sethmrjaipuriya6.jpg",
    ],
    about: "Aerobay started working with Seth MR Jaipuriya, Lucknow in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka, Purnea",
    logo: "/images/clients/15.png",
    joined: "2022",
    principal: "Dr. Moupali Mittra",
    website: "https://www.gdgoenkapurnea.com/",
    testimonial: "",
    location: "Bihar",
    gallery: [
      "/images/gallery/gdgoenkapurnea1.jpg",
      "/images/gallery/gdgoenkapurnea2.jpg",
      "/images/gallery/gdgoenkapurnea3.jpg",
      "/images/gallery/gdgoenkapurnea4.jpg",
      "/images/gallery/gdgoenkapurnea5.jpg",
      "/images/gallery/gdgoenkapurnea6.jpg",
    ],
    about: "Aerobay started working with GD Goenka, Purnea in 2022.",
    board: "CBSE",
  },
  {
    name: "Cohen International, Odisha",
    logo: "/images/clients/16.png",
    joined: "2022",
    principal: "",
    website: "https://www.coheninternationalschool.com/",
    testimonial: "",
    location: "Odisha",
    gallery: [
      "/images/gallery/cohen1.jpg",
      "/images/gallery/cohen2.jpg",
      "/images/gallery/cohen3.jpg",
      "/images/gallery/cohen4.jpg",
      "/images/gallery/cohen5.jpg",
      "/images/gallery/cohen6.jpg",
    ],
    about: "Aerobay started working with Cohen International, Odisha in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka, Siliguri",
    logo: "/images/clients/17.png",
    joined: "2022",
    principal: "Ms. Sonika Sharma",
    website: "https://gdgoenkaschool.in/",
    testimonial: "",
    location: "West Bengal",
    gallery: [
      "/images/gallery/gdgoenkasiliguri1.jpg",
      "/images/gallery/gdgoenkasiliguri2.jpg",
      "/images/gallery/gdgoenkasiliguri3.jpg",
      "/images/gallery/gdgoenkasiliguri4.jpg",
      "/images/gallery/gdgoenkasiliguri5.jpg",
      "/images/gallery/gdgoenkasiliguri6.jpg",
    ],
    about: "Aerobay started working with GD Goenka, Siliguri in 2022.",
    board: "CBSE",
  },
  {
    name: "Trinity Public School, Kolkata",
    logo: "/images/clients/18.png",
    joined: "2022",
    principal: "Ms. Tahseen Mahmood",
    website: "https://www.trinitypublicschool.org/",
    testimonial: "",
    location: "West Bengal",
    gallery: [
      "/images/gallery/trinity1.jpg",
      "/images/gallery/trinity2.jpg",
      "/images/gallery/trinity3.jpg",
      "/images/gallery/trinity4.jpg",
      "/images/gallery/trinity5.jpg",
      "/images/gallery/trinity6.jpg",
    ],
    about: "Aerobay started working with Trinity Public School, Kolkata in 2022.",
    board: "CBSE",
  },
  {
    name: "STEAMFIELD School, Jabalpur",
    logo: "/images/clients/19.png",
    joined: "2022",
    principal: "Ms. Manmeet Kohli",
    website: "https://www.stemfield.com/",
    testimonial: "",
    location: "Madhya Pradesh",
    gallery: [
      "/images/gallery/stemfield1.jpg",
      "/images/gallery/stemfield2.jpg",
      "/images/gallery/stemfield3.jpg",
      "/images/gallery/stemfield4.jpg",
      "/images/gallery/stemfield5.jpg",
      "/images/gallery/stemfield6.jpg",
    ],
    about: "Aerobay started working with STEAMFIELD School, Jabalpur in 2022.",
    board: "CBSE",
  },
  {
    name: "DPS, Nagaon",
    logo: "/images/clients/20.png",
    joined: "2022",
    principal: "Ms. Ritu Rajnish",
    website: "https://dpsnagaon.com/",
    testimonial: "",
    location: "Assam",
    gallery: [
      "/images/gallery/dpsbokaro1.jpg",
      "/images/gallery/dpsbokaro2.jpg",
      "/images/gallery/dpsbokaro3.jpg",
      "/images/gallery/dpsbokaro4.jpg",
      "/images/gallery/dpsbokaro5.jpg",
      "/images/gallery/dpsbokaro6.jpg",
    ],
    about: "Aerobay started working with DPS, Nagaon in 2022.",
    board: "CBSE",
  },
  {
    name: "NPS, Guwahati",
    logo: "/images/clients/21.png",
    joined: "2022",
    principal: "Mr. Akhawari Nil Kishore Sinha",
    website: "https://npsis.in/",
    testimonial: "",
    location: "Assam",
    gallery: [
      "/images/gallery/npsinternationalschool1.jpg",
      "/images/gallery/npsinternationalschool2.jpg",
      "/images/gallery/npsinternationalschool3.jpg",
      "/images/gallery/npsinternationalschool4.jpg",
      "/images/gallery/npsinternationalschool5.jpg",
      "/images/gallery/npsinternationalschool6.jpg",
    ],
    about: "Aerobay started working with NPS, Guwahati in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka, Jabalpur",
    logo: "/images/clients/22.png",
    joined: "2022",
    principal: "Ms. Meenal Madhan",
    website: "https://gdgoenkajabalpur.com/",
    testimonial: "",
    location: "Madhya Pradesh",
    gallery: [
      "/images/gallery/gdgoenkajabalpur1.jpg",
      "/images/gallery/gdgoenkajabalpur2.jpg",
      "/images/gallery/gdgoenkajabalpur3.jpg",
      "/images/gallery/gdgoenkajabalpur4.jpg",
      "/images/gallery/gdgoenkajabalpur5.jpg",
      "/images/gallery/gdgoenkajabalpur6.jpg",
    ],
    about: "Aerobay started working with GD Goenka, Jabalpur in 2022.",
    board: "CBSE",
  },
  {
    name: "Jayshree Periwal International School, Jaipur",
    logo: "/images/clients/23.png",
    joined: "2022",
    principal: "",
    website: "https://jpischool.com/",
    testimonial: "",
    location: "Rajasthan",
    gallery: [
      "/images/gallery/jayshreeperiwal1.jpg",
      "/images/gallery/jayshreeperiwal2.jpg",
      "/images/gallery/jayshreeperiwal3.jpg",
      "/images/gallery/jayshreeperiwal4.jpg",
      "/images/gallery/jayshreeperiwal5.jpg",
      "/images/gallery/jayshreeperiwal6.jpg",
    ],
    about: "Aerobay started working with Jayshree Periwal International School, Jaipur in 2022.",
    board: "IB",
  },
  {
    name: "GH Raisoni, Jalgaon",
    logo: "/images/clients/24.png",
    joined: "2022",
    principal: "Ms. Christabel Perera",
    website: "https://ghrpsjal.raisoni.net/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with GH Raisoni, Jalgaon in 2022.",
    board: "CBSE",
  },
  {
    name: "Narayana Vidyalayam, Nagpur",
    logo: "/images/clients/25.png",
    joined: "2022",
    principal: "Ms. Rekha Nair",
    website: "https://narayanavidyalayam.org/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/narayanavidyalayam1.jpg",
      "/images/gallery/narayanavidyalayam2.jpg",
      "/images/gallery/narayanavidyalayam3.jpg",
      "/images/gallery/narayanavidyalayam4.jpg",
      "/images/gallery/narayanavidyalayam5.jpg",
      "/images/gallery/narayanavidyalayam6.jpg",
    ],
    about: "Aerobay started working with Narayana Vidyalayam, Nagpur in 2022.",
    board: "CBSE",
  },
  {
    name: "Narayana Vidyalayam, Chandrapur",
    logo: "/images/clients/26.png",
    joined: "2022",
    principal: "Ms. Shraboni Banerjee",
    website: "https://narayanavidyalayam.org/principal-message-chandrapur/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/narayanavidyalayam1.jpg",
      "/images/gallery/narayanavidyalayam2.jpg",
      "/images/gallery/narayanavidyalayam3.jpg",
      "/images/gallery/narayanavidyalayam4.jpg",
      "/images/gallery/narayanavidyalayam5.jpg",
      "/images/gallery/narayanavidyalayam6.jpg",
    ],
    about: "Aerobay started working with Narayana Vidyalayam, Chandrapur in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Wanadongri",
    logo: "/images/clients/27.png",
    joined: "2022",
    principal: "Dr kavita nagarajan",
    website: "https://schoolofscholars.edu.in/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Wanadongri in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Atreya Layout",
    logo: "/images/clients/28.png",
    joined: "2022",
    principal: "Ms. Shilpa Newaskar",
    website: "https://schoolofscholars.edu.in/atrey/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Atreya Layout in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Beltarodi",
    logo: "/images/clients/29.png",
    joined: "2022",
    principal: "Ms. Uma Bhalerao",
    website: "https://schoolofscholars.edu.in/beltarodi/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Beltarodi in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Wardha",
    logo: "/images/clients/30.png",
    joined: "2022",
    principal: "Mr. Suresh Lakde",
    website: "https://schoolofscholars.edu.in/wardha/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Wardha in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Amravati",
    logo: "/images/clients/31.png",
    joined: "2022",
    principal: "Mr. N Santosh Kumar",
    website: "https://schoolofscholars.edu.in/amravati/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Amravati in 2022.",
    board: "CBSE",
  },
  {
    name: "SOS Akola",
    logo: "/images/clients/32.png",
    joined: "2022",
    principal: "Mrs. Manisha Umbarkar",
    website: "https://schoolofscholars.edu.in/akolakk/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Akola in 2022.",
    board: "CBSE",
  },
  {
    name: "BD Somani International School, Mumbai",
    logo: "/images/clients/33.png",
    joined: "2022",
    principal: "Ms. Shrutika Lawand",
    website: "https://bdsomaniinternationalschool.com/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/bdsomani1.jpg",
      "/images/gallery/bdsomani2.jpg",
      "/images/gallery/bdsomani3.jpg",
      "/images/gallery/bdsomani4.jpg",
      "/images/gallery/bdsomani5.jpg",
      "/images/gallery/bdsomani6.jpg",
    ],
    about: "Aerobay started working with BD Somani International School, Mumbai in 2022.",
    board: "IB",
  },
  {
    name: "CPS, Dabha road, Nagpur",
    logo: "/images/clients/34.png",
    joined: "2022",
    principal: "Ms. Ashlesha Chintawish",
    website: "https://cpsintl.in/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/centrepoint1.jpg",
      "/images/gallery/centrepoint2.jpg",
      "/images/gallery/centrepoint3.jpg",
      "/images/gallery/centrepoint4.jpg",
      "/images/gallery/centrepoint5.jpg",
      "/images/gallery/centrepoint6.jpg",
    ],
    about: "Aerobay started working with CPS, Dabha road, Nagpur in 2022.",
    board: "Cambridge",
  },
  {
    name: "SOS Yavatmal",
    logo: "/images/clients/35.png",
    joined: "2022",
    principal: "Narendra Chawhan",
    website: "https://schoolofscholars.edu.in/yavatmal/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schoolofscholars1.jpg",
      "/images/gallery/schoolofscholars2.jpg",
      "/images/gallery/schoolofscholars3.jpg",
      "/images/gallery/schoolofscholars4.jpg",
      "/images/gallery/schoolofscholars5.jpg",
      "/images/gallery/schoolofscholars6.jpg",
    ],
    about: "Aerobay started working with SOS Yavatmal in 2022.",
    board: "CBSE",
  },
  {
    name: "Scholar Rosary Imperial, Rohtak",
    logo: "/images/clients/36.png",
    joined: "2022",
    principal: "",
    website: "https://scholarsrosary.co.in/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/scholarsrosarypublicschoolrohtak1.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak2.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak3.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak4.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak5.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak6.jpg",
    ],
    about: "Aerobay started working with Scholar Rosary Imperial, Rohtak in 2022.",
    board: "CBSE",
  },
  {
    name: "Scholar's Rosary, Rohtak",
    logo: "/images/clients/37.png",
    joined: "2022",
    principal: "",
    website: "https://scholarsrosary.co.in/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/scholarsrosarypublicschoolrohtak1.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak2.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak3.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak4.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak5.jpg",
      "/images/gallery/scholarsrosarypublicschoolrohtak6.jpg",
    ],
    about: "Aerobay started working with Scholar's Rosary, Rohtak in 2022.",
    board: "CBSE",
  },
  {
    name: "Patna Central School, Patna",
    logo: "/images/clients/38.png",
    joined: "2022",
    principal: "Mr. Vasisth",
    website: "https://www.centralschoolpatna.com/",
    testimonial: "",
    location: "Bihar",
    gallery: [
      "/images/gallery/acharyashrisudarshan1.jpg",
      "/images/gallery/acharyashrisudarshan2.jpg",
      "/images/gallery/acharyashrisudarshan3.jpg",
      "/images/gallery/acharyashrisudarshan4.jpg",
      "/images/gallery/acharyashrisudarshan5.jpg",
      "/images/gallery/acharyashrisudarshan6.jpg",
    ],
    about: "Aerobay started working with Patna Central School, Patna in 2022.",
    board: "CBSE",
  },
  {
    name: "Birla Open Minds International School, Buxar",
    logo: "/images/clients/39.png",
    joined: "2022",
    principal: "Mr. NS Punia",
    website: "https://birlaopenmindsbuxar.com/",
    testimonial: "",
    location: "Bihar",
    gallery: [
      "/images/gallery/birlaopenmindsbuxar1.jpg",
      "/images/gallery/birlaopenmindsbuxar2.jpg",
      "/images/gallery/birlaopenmindsbuxar3.jpg",
      "/images/gallery/birlaopenmindsbuxar4.jpg",
      "/images/gallery/birlaopenmindsbuxar5.jpg",
      "/images/gallery/birlaopenmindsbuxar6.jpg",
    ],
    about: "Aerobay started working with Birla Open Minds International School, Buxar in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka, Jhansi",
    logo: "/images/clients/40.png",
    joined: "2022",
    principal: "Ms. Paramjeet Kaur",
    website: "https://gdgoenkajhansi.com/principals-desk/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkajabalpur1.jpg",
      "/images/gallery/gdgoenkajabalpur2.jpg",
      "/images/gallery/gdgoenkajabalpur3.jpg",
      "/images/gallery/gdgoenkajabalpur4.jpg",
      "/images/gallery/gdgoenkajabalpur5.jpg",
      "/images/gallery/gdgoenkajabalpur6.jpg",
    ],
    about: "Aerobay started working with GD Goenka, Jhansi in 2022.",
    board: "CBSE",
  },
  {
    name: "DPS, Gangtok",
    logo: "/images/clients/41.png",
    joined: "2022",
    principal: "Mr. Ravindra Varma",
    website: "https://dpsgangtok.com/",
    testimonial: "",
    location: "Sikkim",
    gallery: [
      "/images/gallery/dpsbokaro1.jpg",
      "/images/gallery/dpsbokaro2.jpg",
      "/images/gallery/dpsbokaro3.jpg",
      "/images/gallery/dpsbokaro4.jpg",
      "/images/gallery/dpsbokaro5.jpg",
      "/images/gallery/dpsbokaro6.jpg",
    ],
    about: "Aerobay started working with DPS, Gangtok in 2022.",
    board: "CBSE",
  },
  {
    name: "Schemford",
    logo: "/images/clients/42.png",
    joined: "2022",
    principal: "",
    website: "https://shemford.com/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/schemford1.jpg",
      "/images/gallery/schemford2.jpg",
      "/images/gallery/schemford3.jpg",
      "/images/gallery/schemford4.jpg",
      "/images/gallery/schemford5.jpg",
      "/images/gallery/shemford6.jpg",
    ],
    about: "Aerobay started working with Schemford in 2022.",
    board: "CBSE",
  },
  {
    name: "Stellar World School, Bandra",
    logo: "/images/clients/43.png",
    joined: "2022",
    principal: "",
    website: "https://sws.edu.in/bandra/",
    testimonial: "",
    location: "Maharashtra",
    gallery: [
      "/images/gallery/bdsomani1.jpg",
      "/images/gallery/bdsomani2.jpg",
      "/images/gallery/bdsomani3.jpg",
      "/images/gallery/bdsomani4.jpg",
      "/images/gallery/bdsomani5.jpg",
      "/images/gallery/bdsomani6.jpg",
    ],
    about: "Aerobay started working with Stellar World School, Bandra in 2022.",
    board: "IB",
  },
  {
    name: "Prominence School, Greater Noida",
    logo: "/images/clients/44.png",
    joined: "2022",
    principal: "",
    website: "https://www.prominenceworldschool.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/dlfpublicschool1.jpg",
      "/images/gallery/dlfpublicschool2.jpg",
      "/images/gallery/dlfpublicschool3.jpg",
      "/images/gallery/dlfpublicschool4.jpg",
      "/images/gallery/dlfpublicschool5.jpg",
      "/images/gallery/dlfpublicschool6.jpg",
    ],
    about: "Aerobay started working with Prominence School, Greater Noida in 2022.",
    board: "CBSE",
  },
  {
    name: "Don Bosco School, Kharagpur",
    logo: "/images/clients/45.png",
    joined: "2022",
    principal: "Stanley Anthony",
    website: "https://www.donboscokharagpur.org/",
    testimonial: "",
    location: "West Bengal",
    gallery: [
      "/images/gallery/trinity1.jpg",
      "/images/gallery/trinity2.jpg",
      "/images/gallery/trinity3.jpg",
      "/images/gallery/trinity4.jpg",
      "/images/gallery/trinity5.jpg",
      "/images/gallery/trinity6.jpg",
    ],
    about: "Aerobay started working with Don Bosco School, Kharagpur in 2022.",
    board: "CBSE",
  },
  {
    name: "Digmani Public School Gaya",
    logo: "/images/clients/46.png",
    joined: "2022",
    principal: "Mr. Basanta Kumar",
    website: "https://digmaniglobalschool.org/",
    testimonial: "",
    location: "Bihar",
    gallery: [
      "/images/gallery/RPS1.jpg",
      "/images/gallery/Rps2.jpg",
      "/images/gallery/RPS3.jpg",
      "/images/gallery/RPS4.jpg",
      "/images/gallery/RPS5.jpg",
      "/images/gallery/RPS6.jpg",
    ],
    about: "Aerobay started working with Digmani Public School Gaya in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Shahjahanpur",
    logo: "/images/clients/47.png",
    joined: "2022",
    principal: "Ms. Kalpana Singh",
    website: "https://gdgoenkashahjahanpur.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkasitapur1.jpg",
      "/images/gallery/gdgoenkasitapur2.jpg",
      "/images/gallery/gdgoenkasitapur3.jpg",
      "/images/gallery/gdgoenkasitapur4.jpg",
      "/images/gallery/gdgoenkasitapur5.jpg",
      "/images/gallery/gdgoenkasitapur6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Shahjahanpur in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Firozabad",
    logo: "/images/clients/48.png",
    joined: "2022",
    principal: "Mrs Richa Prakash",
    website: "https://gdgoenkafirozabad.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkasitapur1.jpg",
      "/images/gallery/gdgoenkasitapur2.jpg",
      "/images/gallery/gdgoenkasitapur3.jpg",
      "/images/gallery/gdgoenkasitapur4.jpg",
      "/images/gallery/gdgoenkasitapur5.jpg",
      "/images/gallery/gdgoenkasitapur6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Firozabad in 2022.",
    board: "CBSE",
  },
  {
    name: "Birla Open Mind, BKT Lucknow",
    logo: "/images/clients/49.png",
    joined: "2022",
    principal: "",
    website: "https://www.birlaopenmindslko.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/birlaopenmindsbuxar1.jpg",
      "/images/gallery/birlaopenmindsbuxar2.jpg",
      "/images/gallery/birlaopenmindsbuxar3.jpg",
      "/images/gallery/birlaopenmindsbuxar4.jpg",
      "/images/gallery/birlaopenmindsbuxar5.jpg",
      "/images/gallery/birlaopenmindsbuxar6.jpg",
    ],
    about: "Aerobay started working with Birla Open Mind, BKT Lucknow in 2022.",
    board: "CBSE",
  },
  {
    name: "The Nest, Chennai",
    logo: "/images/clients/50.png",
    joined: "2022",
    principal: "Mrs. Shefali Tewary",
    website: "https://thenest.school/",
    testimonial: "",
    location: "Tamil Nadu",
    gallery: [
      "/images/gallery/fountainhead1.jpg",
      "/images/gallery/fountainhead2.jpg",
      "/images/gallery/fountainhead3.jpg",
      "/images/gallery/fountainhead4.jpg",
      "/images/gallery/fountainhead5.jpg",
      "/images/gallery/fountainhead6.jpg",
    ],
    about: "Aerobay started working with The Nest, Chennai in 2022.",
    board: "IB",
  },
  {
    name: "Fountainhead School, Surat",
    logo: "/images/clients/51.png",
    joined: "2022",
    principal: "Mr. Bill Roberts",
    website: "https://fountainheadschool.org/",
    testimonial: "",
    location: "Gujarat",
    gallery: [
      "/images/gallery/fountainhead1.jpg",
      "/images/gallery/fountainhead2.jpg",
      "/images/gallery/fountainhead3.jpg",
      "/images/gallery/fountainhead4.jpg",
      "/images/gallery/fountainhead5.jpg",
      "/images/gallery/fountainhead6.jpg",
    ],
    about: "Aerobay started working with Fountainhead School, Surat in 2022.",
    board: "IB",
  },
  {
    name: "Amity International School, Gurgaon 46",
    logo: "/images/clients/52.png",
    joined: "2022",
    principal: "Ms. Arti Chopra",
    website: "https://www.amity.edu/ais/gurgaon46/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/amitygurgaon461.jpg",
      "/images/gallery/amitygurgaon462.jpg",
      "/images/gallery/amitygurgaon463.jpg",
      "/images/gallery/amitygurgaon464.jpg",
      "/images/gallery/amitygurgaon465.jpg",
      "/images/gallery/amitygurgaon466.jpg",
    ],
    about: "Aerobay started working with Amity International School, Gurgaon 46 in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Gurgaon 43",
    logo: "/images/clients/53.png",
    joined: "2022",
    principal: "Ms. Anisha Makhija",
    website: "https://www.amity.edu/ais/gurgaon43/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/amitygurgaon431.jpg",
      "/images/gallery/amitygurgaon432.jpg",
      "/images/gallery/amitygurgaon433.jpg",
      "/images/gallery/amitygurgaon434.jpg",
      "/images/gallery/amitygurgaon435.jpg",
      "/images/gallery/amitygurgaon436.jpg",
    ],
    about: "Aerobay started working with Amity International School, Gurgaon 43 in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Sector 6",
    logo: "/images/clients/54.png",
    joined: "2022",
    principal: "Ms. Divya Bhatia",
    website: "https://www.amity.edu/ais/vasundhara6/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/amityvasundhara61.jpg",
      "/images/gallery/amityvasundhara62.jpg",
      "/images/gallery/amityvasundhara63.jpg",
      "/images/gallery/amityvasundhara64.jpg",
      "/images/gallery/amityvasundhara65.jpg",
      "/images/gallery/amityvasundhara66.jpg",
    ],
    about: "Aerobay started working with Amity International School, Sector 6 in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Vasundhara 1",
    logo: "/images/clients/55.png",
    joined: "2022",
    principal: "Ms. Rachna Sharma",
    website: "https://www.amity.edu/ais/vasundhara/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/amityvasundhara1.jpg",
      "/images/gallery/amityvasundhara2.jpg",
      "/images/gallery/amityvasundhara3.jpg",
      "/images/gallery/amityvasundhara4.jpg",
      "/images/gallery/amityvasundhara5.jpg",
      "/images/gallery/amityvasundhara6.jpg",
    ],
    about: "Aerobay started working with Amity International School, Vasundhara 1 in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Pushp Vihar",
    logo: "/images/clients/56.png",
    joined: "2022",
    principal: "Ms. Ameeta Mohan",
    website: "https://www.amity.edu/ais/pushpvihar/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitypushpvihar1.jpg",
      "/images/gallery/amitypushpvihar2.jpg",
      "/images/gallery/amitypushpvihar3.jpg",
      "/images/gallery/amitypushpvihar4.jpg",
      "/images/gallery/amitypushpvihar5.jpg",
      "/images/gallery/amitypushpvihar6.jpg",
    ],
    about: "Aerobay started working with Amity International School, Pushp Vihar in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Saket",
    logo: "/images/clients/57.png",
    joined: "2022",
    principal: "Ms. Jyoti Arora",
    website: "https://www.amity.edu/ais/saket/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitysaket1.jpg",
      "/images/gallery/amitysaket2.jpg",
      "/images/gallery/amitysaket3.jpg",
      "/images/gallery/amitysaket4.jpg",
      "/images/gallery/amitysaket5.jpg",
      "/images/gallery/amitysaket6.jpg",
    ],
    about: "Aerobay started working with Amity International School, Saket in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity International School, Mayur Vihar",
    logo: "/images/clients/58.png",
    joined: "2022",
    principal: "Ms. Sarita Aggarwal",
    website: "https://www.amity.edu/ais/mayurvihar/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitymayurvihar1.jpg",
      "/images/gallery/amitymayurvihar2.jpg",
      "/images/gallery/amitymayurvihar3.jpg",
      "/images/gallery/amitymayurvihar4.jpg",
      "/images/gallery/amitymayurvihar5.jpg",
      "/images/gallery/amitymayurvihar6.jpg",
    ],
    about: "Aerobay started working with Amity International School, Mayur Vihar in 2022.",
    board: "CBSE",
  },
  {
    name: "Amity Global School, Gurgaon 46",
    logo: "/images/clients/59.png",
    joined: "2022",
    principal: "Ms. Arti Chopra",
    website: "https://www.amityglobalschool.com/gurgaon46/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/amitygurgaon461.jpg",
      "/images/gallery/amitygurgaon462.jpg",
      "/images/gallery/amitygurgaon463.jpg",
      "/images/gallery/amitygurgaon464.jpg",
      "/images/gallery/amitygurgaon465.jpg",
      "/images/gallery/amitygurgaon466.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Gurgaon 46 in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Gurgaon 43",
    logo: "/images/clients/60.png",
    joined: "2022",
    principal: "Ms. Anisha Makhija",
    website: "https://www.amityglobalschool.com/gurgaon/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/amitygurgaon431.jpg",
      "/images/gallery/amitygurgaon432.jpg",
      "/images/gallery/amitygurgaon433.jpg",
      "/images/gallery/amitygurgaon434.jpg",
      "/images/gallery/amitygurgaon435.jpg",
      "/images/gallery/amitygurgaon436.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Gurgaon 43 in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Noida",
    logo: "/images/clients/61.png",
    joined: "2022",
    principal: "Ms. Sharma",
    website: "https://www.amityglobalschool.com/noida/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/amitynoida1.jpg",
      "/images/gallery/amitynoida2.jpg",
      "/images/gallery/amitynoida3.jpg",
      "/images/gallery/amitynoida4.jpg",
      "/images/gallery/amitynoida5.jpg",
      "/images/gallery/amitynoida6.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Noida in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Viraj Khand",
    logo: "/images/clients/62.png",
    joined: "2022",
    principal: "Ms. Vineeta Kanwar",
    website: "https://www.amityglobalschool.com/lucknow/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/amityvirajkhand1.jpg",
      "/images/gallery/amityvirajkhand2.jpg",
      "/images/gallery/amityvirajkhand3.jpg",
      "/images/gallery/amityvirajkhand4.jpg",
      "/images/gallery/amityvirajkhand5.jpg",
      "/images/gallery/amityvirajkhand6.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Viraj Khand in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Sector 6",
    logo: "/images/clients/63.png",
    joined: "2022",
    principal: "Ms. Divya Bhatia",
    website: "https://www.amityglobalschool.com/vasundhara/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/amityvasundhara61.jpg",
      "/images/gallery/amityvasundhara62.jpg",
      "/images/gallery/amityvasundhara63.jpg",
      "/images/gallery/amityvasundhara64.jpg",
      "/images/gallery/amityvasundhara65.jpg",
      "/images/gallery/amityvasundhara66.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Sector 6 in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Pushp Vihar",
    logo: "/images/clients/64.png",
    joined: "2022",
    principal: "Ms. Ameeta Mohan",
    website: "https://www.amityglobalschool.com/pushpvihar/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitypushpvihar1.jpg",
      "/images/gallery/amitypushpvihar2.jpg",
      "/images/gallery/amitypushpvihar3.jpg",
      "/images/gallery/amitypushpvihar4.jpg",
      "/images/gallery/amitypushpvihar5.jpg",
      "/images/gallery/amitypushpvihar6.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Pushp Vihar in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Saket",
    logo: "/images/clients/65.png",
    joined: "2022",
    principal: "Ms. Jyoti Arora",
    website: "https://www.amityglobalschool.com/saket/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitysaket1.jpg",
      "/images/gallery/amitysaket2.jpg",
      "/images/gallery/amitysaket3.jpg",
      "/images/gallery/amitysaket4.jpg",
      "/images/gallery/amitysaket5.jpg",
      "/images/gallery/amitysaket6.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Saket in 2022.",
    board: "IB",
  },
  {
    name: "Amity Global School, Mayur Vihar",
    logo: "/images/clients/66.png",
    joined: "2022",
    principal: "Ms. Sarita Aggarwal",
    website: "https://www.amityglobalschool.com/mayurvihar/",
    testimonial: "",
    location: "Delhi",
    gallery: [
      "/images/gallery/amitymayurvihar1.jpg",
      "/images/gallery/amitymayurvihar2.jpg",
      "/images/gallery/amitymayurvihar3.jpg",
      "/images/gallery/amitymayurvihar4.jpg",
      "/images/gallery/amitymayurvihar5.jpg",
      "/images/gallery/amitymayurvihar6.jpg",
    ],
    about: "Aerobay started working with Amity Global School, Mayur Vihar in 2022.",
    board: "IB",
  },
  {
    name: "Scottish High International School, Gurgaon",
    logo: "/images/clients/67.png",
    joined: "2022",
    principal: "Ms. Sudha Goyal",
    website: "https://www.scottishigh.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/scottishhigh1.jpg",
      "/images/gallery/scottishhigh2.jpg",
      "/images/gallery/scottishhigh3.jpg",
      "/images/gallery/scottishhigh4.jpg",
      "/images/gallery/scottishhigh5.jpg",
      "/images/gallery/scottishhigh6.jpg",
    ],
    about: "Aerobay started working with Scottish High International School, Gurgaon in 2022.",
    board: "IB",
  },
  {
    name: "Pathways School, Gurgaon",
    logo: "/images/clients/68.png",
    joined: "2022",
    principal: "Ms. Sonali Gupta",
    website: "https://www.pathways.in/gurgaon/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/pathwaysgurgaon1.jpg",
      "/images/gallery/pathwaysgurgaon2.jpg",
      "/images/gallery/pathwaysgurgaon3.jpg",
      "/images/gallery/pathwaysgurgaon4.jpg",
      "/images/gallery/pathwaysgurgaon5.jpg",
      "/images/gallery/pathwaysgurgaon6.jpg",
    ],
    about: "Aerobay started working with Pathways School, Gurgaon in 2022.",
    board: "IB",
  },
  {
    name: "Pathways School, Noida",
    logo: "/images/clients/69.png",
    joined: "2022",
    principal: "Mr. Brian Cooklin",
    website: "https://www.pathways.in/noida/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/pathwaysnoida1.jpg",
      "/images/gallery/pathwaysnoida2.jpg",
      "/images/gallery/pathwaysnoida3.jpg",
      "/images/gallery/pathwaysnoida4.jpg",
      "/images/gallery/pathwaysnoida5.jpg",
      "/images/gallery/pathwaysnoida6.jpg",
    ],
    about: "Aerobay started working with Pathways School, Noida in 2022.",
    board: "IB",
  },
  {
    name: "Genesis Global School, Noida",
    logo: "/images/clients/70.png",
    joined: "2022",
    principal: "Mr. Madhur Gupta",
    website: "https://www.genesisglobalschool.com/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/genesisglobalschool1.jpg",
      "/images/gallery/genesisglobalschool2.jpg",
      "/images/gallery/genesisglobalschool3.jpg",
      "/images/gallery/genesisglobalschool4.jpg",
      "/images/gallery/genesisglobalschool5.jpg",
      "/images/gallery/genesisglobalschool6.jpg",
    ],
    about: "Aerobay started working with Genesis Global School, Noida in 2022.",
    board: "IB",
  },
  {
    name: "Shiv Nadar School, Noida",
    logo: "/images/clients/71.png",
    joined: "2022",
    principal: "Ms. Shashi Banerjee",
    website: "https://shivnadarschool.edu.in/noida/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/shivnadarnoida1.jpg",
      "/images/gallery/shivnadarnoida2.jpg",
      "/images/gallery/shivnadarnoida3.jpg",
      "/images/gallery/shivnadarnoida4.jpg",
      "/images/gallery/shivnadarnoida5.jpg",
      "/images/gallery/shivnadarnoida6.jpg",
    ],
    about: "Aerobay started working with Shiv Nadar School, Noida in 2022.",
    board: "IB",
  },
  {
    name: "Shiv Nadar School, Faridabad",
    logo: "/images/clients/72.png",
    joined: "2022",
    principal: "Ms. Anju Malhotra",
    website: "https://shivnadarschool.edu.in/faridabad/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/shivnadarfaridabad1.jpg",
      "/images/gallery/shivnadarfaridabad2.jpg",
      "/images/gallery/shivnadarfaridabad3.jpg",
      "/images/gallery/shivnadarfaridabad4.jpg",
      "/images/gallery/shivnadarfaridabad5.jpg",
      "/images/gallery/shivnadarfaridabad6.jpg",
    ],
    about: "Aerobay started working with Shiv Nadar School, Faridabad in 2022.",
    board: "IB",
  },
  {
    name: "The Shriram Millennium School, Noida",
    logo: "/images/clients/73.png",
    joined: "2022",
    principal: "Ms. Uttara Singh",
    website: "https://www.tsmsnoida.com/",
    testimonial: "",
    location: "NCR",
    gallery: [
      "/images/gallery/shriramnoida1.jpg",
      "/images/gallery/shriramnoida2.jpg",
      "/images/gallery/shriramnoida3.jpg",
      "/images/gallery/shriramnoida4.jpg",
      "/images/gallery/shriramnoida5.jpg",
      "/images/gallery/shriramnoida6.jpg",
    ],
    about: "Aerobay started working with The Shriram Millennium School, Noida in 2022.",
    board: "CBSE",
  },
  {
    name: "The Shriram Millennium School, Gurgaon",
    logo: "/images/clients/74.png",
    joined: "2022",
    principal: "Ms. Manjari Singh",
    website: "https://www.tsmsgurgaon.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/shriramgurgaon1.jpg",
      "/images/gallery/shriramgurgaon2.jpg",
      "/images/gallery/shriramgurgaon3.jpg",
      "/images/gallery/shriramgurgaon4.jpg",
      "/images/gallery/shriramgurgaon5.jpg",
      "/images/gallery/shriramgurgaon6.jpg",
    ],
    about: "Aerobay started working with The Shriram Millennium School, Gurgaon in 2022.",
    board: "CBSE",
  },
  {
    name: "The Shriram School, Aravali",
    logo: "/images/clients/75.png",
    joined: "2022",
    principal: "Ms. Neeru Kapur",
    website: "https://www.shriramschool.org/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/shriramaravali1.jpg",
      "/images/gallery/shriramaravali2.jpg",
      "/images/gallery/shriramaravali3.jpg",
      "/images/gallery/shriramaravali4.jpg",
      "/images/gallery/shriramaravali5.jpg",
      "/images/gallery/shriramaravali6.jpg",
    ],
    about: "Aerobay started working with The Shriram School, Aravali in 2022.",
    board: "IB",
  },
  {
    name: "The Shriram School, Moulsari",
    logo: "/images/clients/76.png",
    joined: "2022",
    principal: "Ms. Perveen Sheikh",
    website: "https://www.shriramschool.org/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/shrirammoulsari1.jpg",
      "/images/gallery/shrirammoulsari2.jpg",
      "/images/gallery/shrirammoulsari3.jpg",
      "/images/gallery/shrirammoulsari4.jpg",
      "/images/gallery/shrirammoulsari5.jpg",
      "/images/gallery/shrirammoulsari6.jpg",
    ],
    about: "Aerobay started working with The Shriram School, Moulsari in 2022.",
    board: "IB",
  },
  {
    name: "GD Goenka Public School, Lucknow",
    logo: "/images/clients/77.png",
    joined: "2022",
    principal: "Ms. Sarita Sharma",
    website: "https://gdgoenkalucknow.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkalucknow1.jpg",
      "/images/gallery/gdgoenkalucknow2.jpg",
      "/images/gallery/gdgoenkalucknow3.jpg",
      "/images/gallery/gdgoenkalucknow4.jpg",
      "/images/gallery/gdgoenkalucknow5.jpg",
      "/images/gallery/gdgoenkalucknow6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Lucknow in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Kanpur",
    logo: "/images/clients/78.png",
    joined: "2022",
    principal: "Ms. Rachna Pant",
    website: "https://gdgoenkakanpur.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkakanpur1.jpg",
      "/images/gallery/gdgoenkakanpur2.jpg",
      "/images/gallery/gdgoenkakanpur3.jpg",
      "/images/gallery/gdgoenkakanpur4.jpg",
      "/images/gallery/gdgoenkakanpur5.jpg",
      "/images/gallery/gdgoenkakanpur6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Kanpur in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Bareilly",
    logo: "/images/clients/79.png",
    joined: "2022",
    principal: "Ms. Shalini Tandon",
    website: "https://gdgoenkabareilly.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkabareilly1.jpg",
      "/images/gallery/gdgoenkabareilly2.jpg",
      "/images/gallery/gdgoenkabareilly3.jpg",
      "/images/gallery/gdgoenkabareilly4.jpg",
      "/images/gallery/gdgoenkabareilly5.jpg",
      "/images/gallery/gdgoenkabareilly6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Bareilly in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Agra",
    logo: "/images/clients/80.png",
    joined: "2022",
    principal: "Ms. Puneeta Vohra",
    website: "https://gdgoenkaagra.com/",
    testimonial: "",
    location: "Uttar Pradesh",
    gallery: [
      "/images/gallery/gdgoenkaagra1.jpg",
      "/images/gallery/gdgoenkaagra2.jpg",
      "/images/gallery/gdgoenkaagra3.jpg",
      "/images/gallery/gdgoenkaagra4.jpg",
      "/images/gallery/gdgoenkaagra5.jpg",
      "/images/gallery/gdgoenkaagra6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Agra in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Haldwani",
    logo: "/images/clients/81.png",
    joined: "2022",
    principal: "Ms. Neema Pant",
    website: "https://gdgoenkahaldwani.com/",
    testimonial: "",
    location: "Uttarakhand",
    gallery: [
      "/images/gallery/gdgoenkahaldwani1.jpg",
      "/images/gallery/gdgoenkahaldwani2.jpg",
      "/images/gallery/gdgoenkahaldwani3.jpg",
      "/images/gallery/gdgoenkahaldwani4.jpg",
      "/images/gallery/gdgoenkahaldwani5.jpg",
      "/images/gallery/gdgoenkahaldwani6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Haldwani in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Jammu",
    logo: "/images/clients/82.png",
    joined: "2022",
    principal: "Mr. Sanyam Gupta",
    website: "https://gdgoenkajammu.com/",
    testimonial: "",
    location: "Jammu & Kashmir",
    gallery: [
      "/images/gallery/gdgoenkajammu1.jpg",
      "/images/gallery/gdgoenkajammu2.jpg",
      "/images/gallery/gdgoenkajammu3.jpg",
      "/images/gallery/gdgoenkajammu4.jpg",
      "/images/gallery/gdgoenkajammu5.jpg",
      "/images/gallery/gdgoenkajammu6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Jammu in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Srinagar",
    logo: "/images/clients/83.png",
    joined: "2022",
    principal: "Mr. Alistair R A Freese",
    website: "https://gdgoenkasrinagar.com/",
    testimonial: "",
    location: "Jammu & Kashmir",
    gallery: [
      "/images/gallery/gdgoenkasrinagar1.jpg",
      "/images/gallery/gdgoenkasrinagar2.jpg",
      "/images/gallery/gdgoenkasrinagar3.jpg",
      "/images/gallery/gdgoenkasrinagar4.jpg",
      "/images/gallery/gdgoenkasrinagar5.jpg",
      "/images/gallery/gdgoenkasrinagar6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Srinagar in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Ludhiana",
    logo: "/images/clients/84.png",
    joined: "2022",
    principal: "Ms. Sangeeta Saigal",
    website: "https://gdgoenkaludhiana.com/",
    testimonial: "",
    location: "Punjab",
    gallery: [
      "/images/gallery/gdgoenkaludhiana1.jpg",
      "/images/gallery/gdgoenkaludhiana2.jpg",
      "/images/gallery/gdgoenkaludhiana3.jpg",
      "/images/gallery/gdgoenkaludhiana4.jpg",
      "/images/gallery/gdgoenkaludhiana5.jpg",
      "/images/gallery/gdgoenkaludhiana6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Ludhiana in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Amritsar",
    logo: "/images/clients/85.png",
    joined: "2022",
    principal: "Ms. Archna Sharma",
    website: "https://gdgoenkaamritsar.com/",
    testimonial: "",
    location: "Punjab",
    gallery: [
      "/images/gallery/gdgoenkaamritsar1.jpg",
      "/images/gallery/gdgoenkaamritsar2.jpg",
      "/images/gallery/gdgoenkaamritsar3.jpg",
      "/images/gallery/gdgoenkaamritsar4.jpg",
      "/images/gallery/gdgoenkaamritsar5.jpg",
      "/images/gallery/gdgoenkaamritsar6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Amritsar in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Patiala",
    logo: "/images/clients/86.png",
    joined: "2022",
    principal: "Ms. Jaspreet Kaur",
    website: "https://gdgoenkapatiala.com/",
    testimonial: "",
    location: "Punjab",
    gallery: [
      "/images/gallery/gdgoenkapatiala1.jpg",
      "/images/gallery/gdgoenkapatiala2.jpg",
      "/images/gallery/gdgoenkapatiala3.jpg",
      "/images/gallery/gdgoenkapatiala4.jpg",
      "/images/gallery/gdgoenkapatiala5.jpg",
      "/images/gallery/gdgoenkapatiala6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Patiala in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Bathinda",
    logo: "/images/clients/87.png",
    joined: "2022",
    principal: "Ms. Anju Puri",
    website: "https://gdgoenkabathinda.com/",
    testimonial: "",
    location: "Punjab",
    gallery: [
      "/images/gallery/gdgoenkabathinda1.jpg",
      "/images/gallery/gdgoenkabathinda2.jpg",
      "/images/gallery/gdgoenkabathinda3.jpg",
      "/images/gallery/gdgoenkabathinda4.jpg",
      "/images/gallery/gdgoenkabathinda5.jpg",
      "/images/gallery/gdgoenkabathinda6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Bathinda in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Rohtak",
    logo: "/images/clients/88.png",
    joined: "2022",
    principal: "Ms. Anjali Sharma",
    website: "https://gdgoenkarohtak.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkarohtak1.jpg",
      "/images/gallery/gdgoenkarohtak2.jpg",
      "/images/gallery/gdgoenkarohtak3.jpg",
      "/images/gallery/gdgoenkarohtak4.jpg",
      "/images/gallery/gdgoenkarohtak5.jpg",
      "/images/gallery/gdgoenkarohtak6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Rohtak in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Hisar",
    logo: "/images/clients/89.png",
    joined: "2022",
    principal: "Ms. Nirmal Yadav",
    website: "https://gdgoenkahisar.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkahisar1.jpg",
      "/images/gallery/gdgoenkahisar2.jpg",
      "/images/gallery/gdgoenkahisar3.jpg",
      "/images/gallery/gdgoenkahisar4.jpg",
      "/images/gallery/gdgoenkahisar5.jpg",
      "/images/gallery/gdgoenkahisar6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Hisar in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Karnal",
    logo: "/images/clients/90.png",
    joined: "2022",
    principal: "Ms. Sangeeta Kapoor",
    website: "https://gdgoenkakarnal.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkakarnal1.jpg",
      "/images/gallery/gdgoenkakarnal2.jpg",
      "/images/gallery/gdgoenkakarnal3.jpg",
      "/images/gallery/gdgoenkakarnal4.jpg",
      "/images/gallery/gdgoenkakarnal5.jpg",
      "/images/gallery/gdgoenkakarnal6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Karnal in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Panipat",
    logo: "/images/clients/91.png",
    joined: "2022",
    principal: "Ms. Ritu Sharma",
    website: "https://gdgoenkapanipat.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkapanipat1.jpg",
      "/images/gallery/gdgoenkapanipat2.jpg",
      "/images/gallery/gdgoenkapanipat3.jpg",
      "/images/gallery/gdgoenkapanipat4.jpg",
      "/images/gallery/gdgoenkapanipat5.jpg",
      "/images/gallery/gdgoenkapanipat6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Panipat in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Sonipat",
    logo: "/images/clients/92.png",
    joined: "2022",
    principal: "Ms. Meena Kak",
    website: "https://gdgoenkasonipat.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkasonipat1.jpg",
      "/images/gallery/gdgoenkasonipat2.jpg",
      "/images/gallery/gdgoenkasonipat3.jpg",
      "/images/gallery/gdgoenkasonipat4.jpg",
      "/images/gallery/gdgoenkasonipat5.jpg",
      "/images/gallery/gdgoenkasonipat6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Sonipat in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Kurukshetra",
    logo: "/images/clients/93.png",
    joined: "2022",
    principal: "Ms. Poonam Sharma",
    website: "https://gdgoenkakurukshetra.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkakurukshetra1.jpg",
      "/images/gallery/gdgoenkakurukshetra2.jpg",
      "/images/gallery/gdgoenkakurukshetra3.jpg",
      "/images/gallery/gdgoenkakurukshetra4.jpg",
      "/images/gallery/gdgoenkakurukshetra5.jpg",
      "/images/gallery/gdgoenkakurukshetra6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Kurukshetra in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Ambala",
    logo: "/images/clients/94.png",
    joined: "2022",
    principal: "Ms. Seema Soni",
    website: "https://gdgoenkaambala.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkaambala1.jpg",
      "/images/gallery/gdgoenkaambala2.jpg",
      "/images/gallery/gdgoenkaambala3.jpg",
      "/images/gallery/gdgoenkaambala4.jpg",
      "/images/gallery/gdgoenkaambala5.jpg",
      "/images/gallery/gdgoenkaambala6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Ambala in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Yamunanagar",
    logo: "/images/clients/95.png",
    joined: "2022",
    principal: "Ms. Priti Bali",
    website: "https://gdgoenkayamunanagar.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkayamunanagar1.jpg",
      "/images/gallery/gdgoenkayamunanagar2.jpg",
      "/images/gallery/gdgoenkayamunanagar3.jpg",
      "/images/gallery/gdgoenkayamunanagar4.jpg",
      "/images/gallery/gdgoenkayamunanagar5.jpg",
      "/images/gallery/gdgoenkayamunanagar6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Yamunanagar in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Bhiwani",
    logo: "/images/clients/96.png",
    joined: "2022",
    principal: "Ms. Garima Salwani",
    website: "https://gdgoenkabhiwani.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkabhiwani1.jpg",
      "/images/gallery/gdgoenkabhiwani2.jpg",
      "/images/gallery/gdgoenkabhiwani3.jpg",
      "/images/gallery/gdgoenkabhiwani4.jpg",
      "/images/gallery/gdgoenkabhiwani5.jpg",
      "/images/gallery/gdgoenkabhiwani6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Bhiwani in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Sirsa",
    logo: "/images/clients/97.png",
    joined: "2022",
    principal: "Ms. Neha Kakkar",
    website: "https://gdgoenkasirsa.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkasirsa1.jpg",
      "/images/gallery/gdgoenkasirsa2.jpg",
      "/images/gallery/gdgoenkasirsa3.jpg",
      "/images/gallery/gdgoenkasirsa4.jpg",
      "/images/gallery/gdgoenkasirsa5.jpg",
      "/images/gallery/gdgoenkasirsa6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Sirsa in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Jind",
    logo: "/images/clients/98.png",
    joined: "2022",
    principal: "Ms. Ritu Dhingra",
    website: "https://gdgoenkajind.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkajind1.jpg",
      "/images/gallery/gdgoenkajind2.jpg",
      "/images/gallery/gdgoenkajind3.jpg",
      "/images/gallery/gdgoenkajind4.jpg",
      "/images/gallery/gdgoenkajind5.jpg",
      "/images/gallery/gdgoenkajind6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Jind in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Rewari",
    logo: "/images/clients/99.png",
    joined: "2022",
    principal: "Ms. Meenakshi Yadav",
    website: "https://gdgoenkarewari.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkarewari1.jpg",
      "/images/gallery/gdgoenkarewari2.jpg",
      "/images/gallery/gdgoenkarewari3.jpg",
      "/images/gallery/gdgoenkarewari4.jpg",
      "/images/gallery/gdgoenkarewari5.jpg",
      "/images/gallery/gdgoenkarewari6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Rewari in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Mahendragarh",
    logo: "/images/clients/100.png",
    joined: "2022",
    principal: "Ms. Suman Yadav",
    website: "https://gdgoenkamahendragarh.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkamahendragarh1.jpg",
      "/images/gallery/gdgoenkamahendragarh2.jpg",
      "/images/gallery/gdgoenkamahendragarh3.jpg",
      "/images/gallery/gdgoenkamahendragarh4.jpg",
      "/images/gallery/gdgoenkamahendragarh5.jpg",
      "/images/gallery/gdgoenkamahendragarh6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Mahendragarh in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Charkhi Dadri",
    logo: "/images/clients/101.png",
    joined: "2022",
    principal: "Ms. Ritu Sheoran",
    website: "https://gdgoenkacharkhidadri.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkacharkhidadri1.jpg",
      "/images/gallery/gdgoenkacharkhidadri2.jpg",
      "/images/gallery/gdgoenkacharkhidadri3.jpg",
      "/images/gallery/gdgoenkacharkhidadri4.jpg",
      "/images/gallery/gdgoenkacharkhidadri5.jpg",
      "/images/gallery/gdgoenkacharkhidadri6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Charkhi Dadri in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Palwal",
    logo: "/images/clients/102.png",
    joined: "2022",
    principal: "Ms. Ritu Chaudhary",
    website: "https://gdgoenkapalwal.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkapalwal1.jpg",
      "/images/gallery/gdgoenkapalwal2.jpg",
      "/images/gallery/gdgoenkapalwal3.jpg",
      "/images/gallery/gdgoenkapalwal4.jpg",
      "/images/gallery/gdgoenkapalwal5.jpg",
      "/images/gallery/gdgoenkapalwal6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Palwal in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Narnaul",
    logo: "/images/clients/103.png",
    joined: "2022",
    principal: "Ms. Suman Yadav",
    website: "https://gdgoenkanarnaul.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkanarnaul1.jpg",
      "/images/gallery/gdgoenkanarnaul2.jpg",
      "/images/gallery/gdgoenkanarnaul3.jpg",
      "/images/gallery/gdgoenkanarnaul4.jpg",
      "/images/gallery/gdgoenkanarnaul5.jpg",
      "/images/gallery/gdgoenkanarnaul6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Narnaul in 2022.",
    board: "CBSE",
  },
  {
    name: "GD Goenka Public School, Bawal",
    logo: "/images/clients/104.png",
    joined: "2022",
    principal: "Ms. Meenakshi Yadav",
    website: "https://gdgoenkabawal.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/gdgoenkabawal1.jpg",
      "/images/gallery/gdgoenkabawal2.jpg",
      "/images/gallery/gdgoenkabawal3.jpg",
      "/images/gallery/gdgoenkabawal4.jpg",
      "/images/gallery/gdgoenkabawal5.jpg",
      "/images/gallery/gdgoenkabawal6.jpg",
    ],
    about: "Aerobay started working with GD Goenka Public School, Bawal in 2022.",
    board: "CBSE",
  },
  {
    name: "Euro International School, Gurugram",
    logo: "/images/clients/105.png",
    joined: "2022",
    principal: "Ms. Pooja Malhotra",
    website: "https://www.eurointernationalschool.com/",
    testimonial: "",
    location: "Haryana",
    gallery: [
      "/images/gallery/eurogurugram1.jpg",
      "/images/gallery/eurogurugram2.jpg",
      "/images/gallery/eurogurugram3.jpg",
      "/images/gallery/eurogurugram4.jpg",
      "/images/gallery/eurogurugram5.jpg",
      "/images/gallery/eurogurugram6.jpg",
    ],
    about: "Aerobay started working with Euro International School, Gurugram in 2022.",
    board: "CBSE",
  },
]

export default schools
